### ISSUE TITLE
Repo cloning fails with LFS bandwidth quota limit reached.

### ISSUE THREAD

**Issue by sogartar** [iree-org/iree-test-suites#56]
```
git clone git@github.com:iree-org/iree-test-suites.git
```

```
Error downloading object: sharktank_models/llama3.1/assets/toy_llama.irpa (37f90b4): Smudge error: Error downloading sharktank_models/llama3.1/assets/toy_llama.irpa (37f90b4754197b1e732c43010e3979223136d91f8c843998aa376afc8c997d09): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

I am not sure if this is intended and what is the best practice when working with Git LFS. I actually don't want to resolve and download all files under LFS if I don't have to.

**Comment by ScottTodd** [comment]
I'm still figuring out how to set up billing and add a data pack to increase our LFS budget.

In the meantime...

> I am not sure if this is intended and what is the best practice when working with Git LFS. I actually don't want to resolve and download all files under LFS if I don't have to.

Per https://stackoverflow.com/a/42021818, it looks like setting the `GIT_LFS_SKIP_SMUDGE` environment variable will skip fetching LFS files if you have LFS installed, like this:
```bash
GIT_LFS_SKIP_SMUDGE=1 git clone SERVER-REPOSITORY
```

If you don't have LFS installed then a standard `git clone` should work fine.

**Comment by sogartar** [comment]
@ScottTodd, thank you for the suggestion.
The step that failed was the branch checkout after the clone. I am not sure what is going on, but after the failed clone I did
```
git reset --hard
```
and it seems it resolved the references.

**Comment by ScottTodd** [comment]
If anyone sees errors when pushing (even to a fork) like this:
```
git push scotttodd sharktank-docs

Pushing to https://github.com/ScottTodd/iree-test-suites.git
Uploading LFS objects:   0% (0/6), 0 B | 0 B/s, done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to push some refs to 'https://github.com/ScottTodd/iree-test-suites.git'
```

Run the push with `--no-verify`. See https://stackoverflow.com/questions/36626793/disable-git-lfs-for-a-remote

**Comment by ScottTodd** [comment]
We're still blocked on configuring billing and paying for more git LFS quota. @rsuderman maybe we should switch these files to regular git or mirror them to somewhere like Azure for now.
